### ISSUE TITLE
Sys Class

### ISSUE THREAD

**Issue by mkierzenka** [angelawang24/CS4500_A1_P2#2]
Hello,

The Object interface specified has a "Sys" parent class. Could you please add an interface for this Sys class or remove its usage? We are not sure how you intend to depend on it.

Thanks,
Marcin

**Comment by rebeccamattie** [comment]
Done! Also-- implementation for Sys and our intended implementation for Object.h and String.h can be found on piazza post 166

**Comment by rebeccamattie** [comment]
The Sys class can be found in helper.h. Implementation can be found on piazza post 166
