### ISSUE TITLE
test-queue.cpp issue

### ISSUE THREAD

**Issue by dodecahedronal** [angelawang24/CS4500_A1_P2#3]
I’m having problems compiling test-queue.cpp (line 9) because the “Cout” class is not defined anywhere. I believe this problem is fixed when changing all mentions of “Cout” with “Sys”. Could I ask that you implement this change?

**Comment by angelawang24** [comment]
Fixed: [Commit](https://github.com/angelawang24/CS4500_A1_P2/commit/c24e3f31a2b3d72abf57e93c4866b068495a2ae4)
