### ISSUE TITLE
Proposed change: creating StringQueue class

### ISSUE THREAD

**Issue by chasebroder** [angelawang24/CS4500_A1_P2#4]
Hello,

We'd like to have a queue class specifically dealing with Strings. It would inherit from Object, and have a very similar interface as Queue. However the following method signatures would have to change: void push(Object *o)-> void push(String* s), Object* pop() -> String* pop(). These proposals are based off Piazza post 341 (https://piazza.com/class/k51bluky59n2jr?cid=341) and the ensuing conversation, which shows an example of calling 'pop' on the string queue and returning a string. 

Let us know what you think of this addition!

Thanks,
Chase

**Comment by angelawang24** [comment]
Hi,

It's not necessary to add another StringQueue class since String should inherit from the Object class. Based off the piazza post, if you really want to use the String class when calling pop, just cast it to the appropriate class but everything should work without the need to cast.

Let me know if you still have issues
Angela

**Comment by chasebroder** [comment]
Hi Angela,

We are concerned about the cost dynamic casting will have on the program. Despite the code duplication that would be needed for a StringQueue, not having to dynamic cast could provide a performance benefit. Also, given the current state of the queue, we would have no way to verify that a string queue contains just strings. 

Let me know what you think of this. With the interface as is, we'd likely use dynamic cast if needed.

Thanks,
Chase

**Comment by angelawang24** [comment]
HI Chase,

The only time you would need dynamic casting is when testing, which I believe is fine. We have been implementing dynamic casting on our side too.

Best,
Angela

**Comment by dodecahedronal** [comment]
Hi all, 

I agree with Angela on this issue. For example, in Java, there is simply an Arraylist type that takes in Objects, and these Objects can be anything. If we start creating specific subclasses for every possible type of Object out there, the codebase would become impossible to maintain. This is just the concept of polymorphism. I think the way the Queue is currently set up is most efficient.

**Comment by chasebroder** [comment]
This sounds good to me. I'll go ahead and close the issue
