### ISSUE TITLE
Question on one of tests

### ISSUE THREAD

**Issue by chasebroder** [angelawang24/CS4500_A1_P2#6]
Hi,

I'm currently failing one of the queue tests (test_queue_equals_object). My current implementation of object checks for equality based on the memory addresses. With this implementation, s would not equal s1, t would not equal t1, and so on, causing the queues to not be equal.

I was wondering if I could gain some insight into your interpretation of equal objects, so I can adjust my implementations as needed. I appreciate the help!

Thanks,
Chase

**Comment by angelawang24** [comment]
Oh I realized something is off about our equals test. It should check that the contents of the queue are equal. I will make that change

**Comment by angelawang24** [comment]
Fixed now. Let me know if there are any other issues
